Removed "type": "module" from package.json to prevent module errors Per https://tamagui.dev/docs/guides/vite#installation > Remove "type": "module" from your package.json if you have it. (The type module support was removed because it was breaking metro, webpack or something).
For reference, error message looked like:
> failed to load config from vite.config.ts ....
> error when starting dev server: ...
> import { tamaguiExtractPlugin, tamaguiPlugin } from ...
> SyntaxError: Named export 'tamaguiExtractPlugin' not found ...